# Generated by Django 5.1.2 on 2024-10-24 17:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usersubmission_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='feature_importance_graph',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='media/feature_importance_graphs'), upload_to=''),
        ),
    ]
