# Generated by Django 5.1.2 on 2024-10-24 22:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_usersubmission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='feature_importance_graph',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/feature_importance_graphs/', location='media/feature_importance_graphs'), upload_to=''),
        ),
    ]
