# Generated by Django 5.1.2 on 2024-10-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_usersubmission_num_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
